### ISSUE TITLE
Source archived

### ISSUE THREAD

**Issue by TechnologyClassroom** [jpsspm/sspm#2]
The source code is bundled as a release [here](https://github.com/jpsspm/sspm/releases/tag/1.0.0) instead of in the [git repo](https://github.com/jpsspm/sspm.git).  I would recommend extracting all of the files into the git repo so that others are able to browse and read the code, easily search through the code, and modify and submit pull requests to the code.

**Comment by jpsspm** [comment]
Answer: TechnologyClassroom

I think it's solved, 
                      I haven't got my bearings on github yet

**Comment by TechnologyClassroom** [comment]
Looks right!
